USE [master]
GO
/****** Object:  Database [QuanLyThuVien]    Script Date: 1/8/2025 4:53:37 PM ******/
CREATE DATABASE [QuanLyThuVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyThuVien', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuanLyThuVien.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyThuVien_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuanLyThuVien_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QuanLyThuVien] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyThuVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLyThuVien] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QuanLyThuVien] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyThuVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLyThuVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuanLyThuVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyThuVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLyThuVien] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLyThuVien] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyThuVien] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyThuVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLyThuVien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanLyThuVien] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanLyThuVien] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QuanLyThuVien] SET QUERY_STORE = OFF
GO
USE [QuanLyThuVien]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[IDAccount] [varchar](50) NOT NULL,
	[PasswordAccount] [varchar](100) NOT NULL,
	[TypeOfAccount] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[IDAdmin] [varchar](50) NOT NULL,
	[IDAccount] [varchar](50) NOT NULL,
	[NameAdmin] [nvarchar](100) NOT NULL,
	[Birthday] [datetime] NOT NULL,
	[Address] [nvarchar](200) NULL,
	[Email] [varchar](100) NOT NULL,
	[NumberPhone] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ADMIN] PRIMARY KEY CLUSTERED 
(
	[IDAdmin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ADMIN_IDAccount] UNIQUE NONCLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BCTKMUONSACH]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BCTKMUONSACH](
	[MaBCTKMuonSach] [varchar](50) NOT NULL,
	[Thang] [date] NOT NULL,
	[TongSoLuotMuon] [int] NOT NULL,
 CONSTRAINT [PK_BCTKMuonSach] PRIMARY KEY CLUSTERED 
(
	[MaBCTKMuonSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BCTKTRATRE]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BCTKTRATRE](
	[MaBCTKTraTre] [varchar](50) NOT NULL,
	[Ngay] [date] NOT NULL,
 CONSTRAINT [PK_BCTKTraTre] PRIMARY KEY CLUSTERED 
(
	[MaBCTKTraTre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETPHANQUYEN]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETPHANQUYEN](
	[IDAccount] [varchar](50) NOT NULL,
	[IDPer] [varchar](50) NOT NULL,
	[suspended] [bit] NOT NULL,
 CONSTRAINT [PK_CHITIETPHANQUYEN] PRIMARY KEY CLUSTERED 
(
	[IDPer] ASC,
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTBCTKMUONSACH]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTBCTKMUONSACH](
	[MaBCTKMuonSach] [varchar](50) NOT NULL,
	[MaTheLoai] [varchar](50) NOT NULL,
	[SoLuotMuon] [int] NOT NULL,
	[TiLe] [float] NOT NULL,
 CONSTRAINT [PK_CTBCTKMuonSach] PRIMARY KEY CLUSTERED 
(
	[MaBCTKMuonSach] ASC,
	[MaTheLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTBCTKTRATRE]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTBCTKTRATRE](
	[MaBCTKTraTre] [varchar](50) NOT NULL,
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[SoNgayTraTre] [int] NOT NULL,
 CONSTRAINT [PK_CTBCTKTRATRE] PRIMARY KEY CLUSTERED 
(
	[MaBCTKTraTre] ASC,
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTPHIEUMUON]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPHIEUMUON](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[HanTra] [datetime] NOT NULL,
	[TinhTrangMuon] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_CTPHIEUMUON] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DOCGIA]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOCGIA](
	[MaDocGia] [varchar](50) NOT NULL,
	[HoTen] [nvarchar](200) NOT NULL,
	[NgaySinh] [date] NOT NULL,
	[DiaChi] [nvarchar](200) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[NgayLapThe] [date] NOT NULL,
	[NgayHetHan] [date] NOT NULL,
	[MaLoaiDocGia] [varchar](50) NOT NULL,
	[IDAccount] [varchar](50) NOT NULL,
	[SDT] [varchar](50) NOT NULL,
	[TongNo] [decimal](18, 0) NOT NULL,
	[GioiThieu] [nvarchar](500) NULL,
 CONSTRAINT [PK_DOCGIA] PRIMARY KEY CLUSTERED 
(
	[MaDocGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DOCGIA_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DOCGIA_IDUser] UNIQUE NONCLUSTERED 
(
	[IDAccount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIDOCGIA]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIDOCGIA](
	[MaLoaiDocGia] [varchar](50) NOT NULL,
	[TenLoaiDocGia] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_LOAIDOCGIA] PRIMARY KEY CLUSTERED 
(
	[MaLoaiDocGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION](
	[IDPer] [varchar](50) NOT NULL,
	[NamePer] [nvarchar](100) NOT NULL,
	[CodeAction] [varchar](100) NOT NULL,
	[Description] [nvarchar](200) NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[IDPer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUMUONSACH]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUMUONSACH](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaDocGia] [varchar](50) NOT NULL,
	[NgayMuon] [date] NOT NULL,
 CONSTRAINT [PK_PHIEUMUONSACH] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUTHUTIENPHAT]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUTHUTIENPHAT](
	[MaPhieuThuTP] [varchar](50) NOT NULL,
	[MaDocGia] [varchar](50) NOT NULL,
	[TongNo] [decimal](18, 0) NOT NULL,
	[SoTienThu] [decimal](18, 0) NOT NULL,
	[ConLai] [decimal](18, 0) NOT NULL,
	[NgayThu] [datetime] NOT NULL,
 CONSTRAINT [PK_PHIEUTHUTIENPHAT] PRIMARY KEY CLUSTERED 
(
	[MaPhieuThuTP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUTRASACH]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUTRASACH](
	[MaPhieuMS] [varchar](50) NOT NULL,
	[MaSach] [varchar](50) NOT NULL,
	[NgayTra] [date] NOT NULL,
	[SoNgayMuon] [int] NOT NULL,
	[TienPhat] [decimal](18, 0) NOT NULL,
	[TinhTrangTraSach] [nvarchar](200) NOT NULL,
	[GhiChu] [nvarchar](200) NULL,
 CONSTRAINT [PK_PHIEUTRASACH] PRIMARY KEY CLUSTERED 
(
	[MaPhieuMS] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SACH](
	[MaSach] [varchar](50) NOT NULL,
	[TenSach] [nvarchar](100) NOT NULL,
	[MaTheLoai] [varchar](50) NOT NULL,
	[NamXuatBan] [int] NOT NULL,
	[NhaXuatBan] [nvarchar](100) NULL,
	[MaTacGia] [varchar](50) NOT NULL,
	[NgayNhap] [date] NOT NULL,
	[TriGia] [decimal](18, 0) NOT NULL,
	[MaTinhTrang] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED 
(
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TACGIA](
	[MaTacGia] [varchar](50) NOT NULL,
	[TenTacGia] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TACGIA] PRIMARY KEY CLUSTERED 
(
	[MaTacGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THAMSO]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THAMSO](
	[MaThamSo] [int] IDENTITY(1,1) NOT NULL,
	[TuoiToiDa] [int] NOT NULL,
	[TuoiToiThieu] [int] NOT NULL,
	[ThoiHanThe] [int] NOT NULL,
	[KhoangCachXB] [int] NOT NULL,
	[SoNgayMuonMax] [int] NOT NULL,
	[SoSachMuonMax] [int] NOT NULL,
	[TPTraTreMotNgay] [decimal](18, 0) NOT NULL,
	[SoLuongTheLoaiMax] [int] NOT NULL,
	[SoLuongTacGia] [int] NOT NULL,
 CONSTRAINT [PK_THAMSO] PRIMARY KEY CLUSTERED 
(
	[MaThamSo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THELOAI]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THELOAI](
	[MaTheLoai] [varchar](50) NOT NULL,
	[TenTheLoai] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_THELOAI] PRIMARY KEY CLUSTERED 
(
	[MaTheLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TINHTRANG]    Script Date: 1/8/2025 4:53:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TINHTRANG](
	[MaTinhTrang] [varchar](50) NOT NULL,
	[TenTinhTrang] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TINHTRANG] PRIMARY KEY CLUSTERED 
(
	[MaTinhTrang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] ADD  CONSTRAINT [DF_CTBCTKTRATRE_SoNgayTraTre]  DEFAULT ((0)) FOR [SoNgayTraTre]
GO
ALTER TABLE [dbo].[DOCGIA] ADD  CONSTRAINT [DF_DOCGIA_TongNo]  DEFAULT ((0)) FOR [TongNo]
GO
ALTER TABLE [dbo].[PHIEUTRASACH] ADD  CONSTRAINT [DF_PHIEUTRASACH_TienPhat]  DEFAULT ((0)) FOR [TienPhat]
GO
ALTER TABLE [dbo].[ADMIN]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_ACCOUNT] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[ADMIN] CHECK CONSTRAINT [FK_ADMIN_ACCOUNT]
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHANQUYEN_ACCOUNT] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN] CHECK CONSTRAINT [FK_CHITIETPHANQUYEN_ACCOUNT]
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHANQUYEN_PERMISSION] FOREIGN KEY([IDPer])
REFERENCES [dbo].[PERMISSION] ([IDPer])
GO
ALTER TABLE [dbo].[CHITIETPHANQUYEN] CHECK CONSTRAINT [FK_CHITIETPHANQUYEN_PERMISSION]
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKMUONSACH_BCTKMUONSACH] FOREIGN KEY([MaBCTKMuonSach])
REFERENCES [dbo].[BCTKMUONSACH] ([MaBCTKMuonSach])
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH] CHECK CONSTRAINT [FK_CTBCTKMUONSACH_BCTKMUONSACH]
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKMUONSACH_THELOAI] FOREIGN KEY([MaTheLoai])
REFERENCES [dbo].[THELOAI] ([MaTheLoai])
GO
ALTER TABLE [dbo].[CTBCTKMUONSACH] CHECK CONSTRAINT [FK_CTBCTKMUONSACH_THELOAI]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKTRATRE_BCTKTRATRE] FOREIGN KEY([MaBCTKTraTre])
REFERENCES [dbo].[BCTKTRATRE] ([MaBCTKTraTre])
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] CHECK CONSTRAINT [FK_CTBCTKTRATRE_BCTKTRATRE]
GO
ALTER TABLE [dbo].[CTBCTKTRATRE]  WITH CHECK ADD  CONSTRAINT [FK_CTBCTKTRATRE_PHIEUTRASACH] FOREIGN KEY([MaPhieuMS], [MaSach])
REFERENCES [dbo].[PHIEUTRASACH] ([MaPhieuMS], [MaSach])
GO
ALTER TABLE [dbo].[CTBCTKTRATRE] CHECK CONSTRAINT [FK_CTBCTKTRATRE_PHIEUTRASACH]
GO
ALTER TABLE [dbo].[CTPHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUMUON_PHIEUMUONSACH] FOREIGN KEY([MaPhieuMS])
REFERENCES [dbo].[PHIEUMUONSACH] ([MaPhieuMS])
GO
ALTER TABLE [dbo].[CTPHIEUMUON] CHECK CONSTRAINT [FK_CTPHIEUMUON_PHIEUMUONSACH]
GO
ALTER TABLE [dbo].[CTPHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUMUON_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CTPHIEUMUON] CHECK CONSTRAINT [FK_CTPHIEUMUON_SACH]
GO
ALTER TABLE [dbo].[DOCGIA]  WITH CHECK ADD  CONSTRAINT [FK_DOCGIA_LOAIDOCGIA] FOREIGN KEY([MaLoaiDocGia])
REFERENCES [dbo].[LOAIDOCGIA] ([MaLoaiDocGia])
GO
ALTER TABLE [dbo].[DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_LOAIDOCGIA]
GO
ALTER TABLE [dbo].[DOCGIA]  WITH CHECK ADD  CONSTRAINT [FK_DOCGIA_USER] FOREIGN KEY([IDAccount])
REFERENCES [dbo].[ACCOUNT] ([IDAccount])
GO
ALTER TABLE [dbo].[DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_USER]
GO
ALTER TABLE [dbo].[PHIEUMUONSACH]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA] FOREIGN KEY([MaDocGia])
REFERENCES [dbo].[DOCGIA] ([MaDocGia])
GO
ALTER TABLE [dbo].[PHIEUMUONSACH] CHECK CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA]
GO
ALTER TABLE [dbo].[PHIEUTHUTIENPHAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUTIENPHAT_DOCGIA] FOREIGN KEY([MaDocGia])
REFERENCES [dbo].[DOCGIA] ([MaDocGia])
GO
ALTER TABLE [dbo].[PHIEUTHUTIENPHAT] CHECK CONSTRAINT [FK_PHIEUTHUTIENPHAT_DOCGIA]
GO
ALTER TABLE [dbo].[PHIEUTRASACH]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTRASACH_CTPHIEUMUON] FOREIGN KEY([MaPhieuMS], [MaSach])
REFERENCES [dbo].[CTPHIEUMUON] ([MaPhieuMS], [MaSach])
GO
ALTER TABLE [dbo].[PHIEUTRASACH] CHECK CONSTRAINT [FK_PHIEUTRASACH_CTPHIEUMUON]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TACGIA] FOREIGN KEY([MaTacGia])
REFERENCES [dbo].[TACGIA] ([MaTacGia])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TACGIA]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_THELOAI] FOREIGN KEY([MaTheLoai])
REFERENCES [dbo].[THELOAI] ([MaTheLoai])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_THELOAI]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TINHTRANG] FOREIGN KEY([MaTinhTrang])
REFERENCES [dbo].[TINHTRANG] ([MaTinhTrang])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TINHTRANG]
GO
USE [master]
GO
ALTER DATABASE [QuanLyThuVien] SET  READ_WRITE 
GO
